"""Prompt modules for each reasoning agent."""

from .activities import ACTIVITY_INSTRUCTION
from .blueprint import BLUEPRINT_INSTRUCTION
from .chunks import ACTIVITY_CHUNK_INSTRUCTION, SCENE_CHUNK_INSTRUCTION
from .common import COMMON_INSTRUCTION
from .media import MEDIA_PLAN_INSTRUCTION, VIDEO_GATE_INSTRUCTION
from .repair import REPAIR_INSTRUCTION
from .storyline import STORYLINE_INSTRUCTION
from .topics import (
    TOPIC_RESOLVER_INSTRUCTION,
    TOPIC_SCOUT_INSTRUCTION,
    TOPIC_SELECTOR_INSTRUCTION,
)
from .validator import VALIDATOR_INSTRUCTION

__all__ = [
    "ACTIVITY_INSTRUCTION",
    "ACTIVITY_CHUNK_INSTRUCTION",
    "BLUEPRINT_INSTRUCTION",
    "COMMON_INSTRUCTION",
    "MEDIA_PLAN_INSTRUCTION",
    "REPAIR_INSTRUCTION",
    "SCENE_CHUNK_INSTRUCTION",
    "STORYLINE_INSTRUCTION",
    "TOPIC_SCOUT_INSTRUCTION",
    "TOPIC_RESOLVER_INSTRUCTION",
    "TOPIC_SELECTOR_INSTRUCTION",
    "VALIDATOR_INSTRUCTION",
    "VIDEO_GATE_INSTRUCTION",
]
