"""create backend contract tables

Revision ID: 758f8d74baca
Revises:
Create Date: 2026-08-19 22:08:18.237154

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "758f8d74baca"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=80), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_code", sa.Integer(), nullable=False),
        sa.Column(
            "response_body",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("scope", "key", name=op.f("uq_idempotency_keys_scope")),
    )
    op.create_table(
        "learners",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("preferred_difficulty", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("allow_generated_stories", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learners")),
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("job_id", sa.String(length=128), nullable=False),
        sa.Column("asset_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("scan_state", sa.String(length=24), nullable=False),
        sa.Column("commit_state", sa.String(length=24), nullable=False),
        sa.Column("cdn_url", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_media_assets_positive_byte_size")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("job_id", "asset_key", name=op.f("uq_media_assets_job_id")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_assets_storage_key")),
    )
    op.create_index(
        op.f("ix_media_assets_commit_state"), "media_assets", ["commit_state"], unique=False
    )
    op.create_index(op.f("ix_media_assets_job_id"), "media_assets", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_media_assets_scan_state"), "media_assets", ["scan_state"], unique=False
    )
    op.create_table(
        "generated_stories",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("learner_id", sa.String(length=128), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
            name=op.f("fk_generated_stories_learner_id_learners"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_stories")),
    )
    op.create_index(
        op.f("ix_generated_stories_learner_id"), "generated_stories", ["learner_id"], unique=False
    )
    op.create_index(
        op.f("ix_generated_stories_status"), "generated_stories", ["status"], unique=False
    )
    op.create_table(
        "learner_preference_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("learner_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("tag", sa.String(length=120), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('affinity', 'fatigue')", name=op.f("ck_learner_preference_tags_valid_kind")
        ),
        sa.CheckConstraint(
            "evidence_count > 0", name=op.f("ck_learner_preference_tags_positive_evidence_count")
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
            name=op.f("fk_learner_preference_tags_learner_id_learners"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_preference_tags")),
        sa.UniqueConstraint(
            "learner_id", "kind", "tag", name=op.f("uq_learner_preference_tags_learner_id")
        ),
    )
    op.create_index(
        op.f("ix_learner_preference_tags_learner_id"),
        "learner_preference_tags",
        ["learner_id"],
        unique=False,
    )
    op.create_table(
        "story_generation_jobs",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("learner_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 1", name=op.f("ck_story_generation_jobs_valid_progress")
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
            name=op.f("fk_story_generation_jobs_learner_id_learners"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_generation_jobs")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_story_generation_jobs_idempotency_key")
        ),
    )
    op.create_index(
        op.f("ix_story_generation_jobs_learner_id"),
        "story_generation_jobs",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_story_generation_jobs_status"), "story_generation_jobs", ["status"], unique=False
    )
    op.create_index(
        "ix_jobs_status_created_at",
        "story_generation_jobs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "generated_story_versions",
        sa.Column("story_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("subject_domain", sa.String(length=80), nullable=False),
        sa.Column("subject_discipline", sa.String(length=120), nullable=False),
        sa.Column("difficulty", sa.String(length=16), nullable=False),
        sa.Column("target_age", sa.Integer(), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=False),
        sa.Column(
            "bundle",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "validation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "target_age >= 15 AND target_age <= 23",
            name=op.f("ck_generated_story_versions_valid_target_age"),
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["generated_stories.id"],
            name=op.f("fk_generated_story_versions_story_id_generated_stories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("story_id", "version", name=op.f("pk_generated_story_versions")),
    )
    op.create_index(
        "ix_story_versions_subject",
        "generated_story_versions",
        ["subject_domain", "subject_discipline"],
        unique=False,
    )
    op.create_table(
        "learner_story_engagement",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("learner_id", sa.String(length=128), nullable=False),
        sa.Column("story_id", sa.String(length=80), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("subject_domain", sa.String(length=80), nullable=False),
        sa.Column("subject_discipline", sa.String(length=120), nullable=False),
        sa.Column(
            "topic_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completion_ratio", sa.Float(), nullable=False),
        sa.Column("active_seconds", sa.Integer(), nullable=False),
        sa.Column("activity_correct", sa.Integer(), nullable=False),
        sa.Column("activity_total", sa.Integer(), nullable=False),
        sa.Column("hints_used", sa.Integer(), nullable=False),
        sa.Column("replayed", sa.Boolean(), nullable=False),
        sa.Column("learner_rating", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "active_seconds >= 0",
            name=op.f("ck_learner_story_engagement_nonnegative_active_seconds"),
        ),
        sa.CheckConstraint(
            "completion_ratio >= 0 AND completion_ratio <= 1",
            name=op.f("ck_learner_story_engagement_valid_completion_ratio"),
        ),
        sa.CheckConstraint(
            "hints_used >= 0", name=op.f("ck_learner_story_engagement_nonnegative_hints_used")
        ),
        sa.CheckConstraint(
            "learner_rating IS NULL OR (learner_rating >= 1 AND learner_rating <= 5)",
            name=op.f("ck_learner_story_engagement_valid_learner_rating"),
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
            name=op.f("fk_learner_story_engagement_learner_id_learners"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["generated_stories.id"],
            name=op.f("fk_learner_story_engagement_story_id_generated_stories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_story_engagement")),
        sa.UniqueConstraint(
            "learner_id",
            "story_id",
            "session_id",
            name=op.f("uq_learner_story_engagement_learner_id"),
        ),
    )
    op.create_index(
        op.f("ix_learner_story_engagement_learner_id"),
        "learner_story_engagement",
        ["learner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learner_story_engagement_story_id"),
        "learner_story_engagement",
        ["story_id"],
        unique=False,
    )
    op.create_index(
        "ix_engagement_learner_completed_at",
        "learner_story_engagement",
        ["learner_id", "completed_at"],
        unique=False,
    )
    op.create_table(
        "story_activities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("story_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.String(length=128), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column(
            "activity",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["story_id", "version"],
            ["generated_story_versions.story_id", "generated_story_versions.version"],
            name=op.f("fk_story_activities_story_id_generated_story_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_activities")),
        sa.UniqueConstraint(
            "story_id", "version", "activity_id", name=op.f("uq_story_activities_story_id")
        ),
    )
    op.create_table(
        "story_asset_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("story_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(length=80), nullable=False),
        sa.Column("asset_key", sa.String(length=128), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=True),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("provider_model", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["media_assets.id"],
            name=op.f("fk_story_asset_links_asset_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["story_id", "version"],
            ["generated_story_versions.story_id", "generated_story_versions.version"],
            name=op.f("fk_story_asset_links_story_id_generated_story_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_asset_links")),
        sa.UniqueConstraint(
            "story_id", "version", "asset_key", name=op.f("uq_story_asset_links_story_id")
        ),
    )
    op.create_table(
        "story_embeddings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("story_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("embedding_id", sa.String(length=128), nullable=False),
        sa.Column("content_key", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=24), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("vector", sa.JSON().with_variant(Vector(768), "postgresql"), nullable=False),
        sa.CheckConstraint("dimensions = 768", name=op.f("ck_story_embeddings_dimensions_768")),
        sa.ForeignKeyConstraint(
            ["story_id", "version"],
            ["generated_story_versions.story_id", "generated_story_versions.version"],
            name=op.f("fk_story_embeddings_story_id_generated_story_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_embeddings")),
        sa.UniqueConstraint(
            "story_id", "version", "content_key", name=op.f("uq_story_embeddings_story_id")
        ),
    )
    op.create_index(
        "ix_story_embeddings_vector_hnsw",
        "story_embeddings",
        ["vector"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    op.create_table(
        "story_scenes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("story_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("scene_id", sa.String(length=64), nullable=False),
        sa.Column("act", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "scene",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["story_id", "version"],
            ["generated_story_versions.story_id", "generated_story_versions.version"],
            name=op.f("fk_story_scenes_story_id_generated_story_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_scenes")),
        sa.UniqueConstraint(
            "story_id", "version", "scene_id", name=op.f("uq_story_scenes_story_id")
        ),
    )
    op.create_table(
        "story_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("story_id", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_name", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["story_id", "version"],
            ["generated_story_versions.story_id", "generated_story_versions.version"],
            name=op.f("fk_story_sources_story_id_generated_story_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_story_sources")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("story_sources")
    op.drop_table("story_scenes")
    op.drop_index("ix_story_embeddings_vector_hnsw", table_name="story_embeddings")
    op.drop_table("story_embeddings")
    op.drop_table("story_asset_links")
    op.drop_table("story_activities")
    op.drop_index("ix_engagement_learner_completed_at", table_name="learner_story_engagement")
    op.drop_index(
        op.f("ix_learner_story_engagement_story_id"), table_name="learner_story_engagement"
    )
    op.drop_index(
        op.f("ix_learner_story_engagement_learner_id"), table_name="learner_story_engagement"
    )
    op.drop_table("learner_story_engagement")
    op.drop_index("ix_story_versions_subject", table_name="generated_story_versions")
    op.drop_table("generated_story_versions")
    op.drop_index("ix_jobs_status_created_at", table_name="story_generation_jobs")
    op.drop_index(op.f("ix_story_generation_jobs_status"), table_name="story_generation_jobs")
    op.drop_index(op.f("ix_story_generation_jobs_learner_id"), table_name="story_generation_jobs")
    op.drop_table("story_generation_jobs")
    op.drop_index(
        op.f("ix_learner_preference_tags_learner_id"), table_name="learner_preference_tags"
    )
    op.drop_table("learner_preference_tags")
    op.drop_index(op.f("ix_generated_stories_status"), table_name="generated_stories")
    op.drop_index(op.f("ix_generated_stories_learner_id"), table_name="generated_stories")
    op.drop_table("generated_stories")
    op.drop_index(op.f("ix_media_assets_scan_state"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_job_id"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_commit_state"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_table("learners")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
